# Generated by Django 4.2.3 on 2023-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_todo_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_animation',
            field=models.BooleanField(default=True),
        ),
    ]
