# Generated by Django 4.2.3 on 2023-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_todo_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
