# Generated by Django 4.2.3 on 2023-08-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_todo_todo_animation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_animation',
        ),
    ]
