# Generated by Django 4.2.3 on 2023-08-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_todo_task_asc_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_asc_priority',
        ),
    ]
