# Generated by Django 4.2.3 on 2023-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_todo_todo_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_asc_priority',
            field=models.BooleanField(default=False),
        ),
    ]
