# Generated by Django 4.2.3 on 2023-08-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_another'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Another',
        ),
    ]
